### ISSUE TITLE
JS/CORS error on link click

### ISSUE THREAD

**Issue by rpavlov** [alexduloz/superyesmore#5]
Hey there, the link "Thing 3" on this page https://superyesmore.com/im-more-than-the-things-i-do-0f4fbbda9439edb16cc21d1875c77003 yields

`Uncaught DOMException: Blocked a frame with origin "https://superyesmore.com" from accessing a cross-origin frame.
    at HTMLIFrameElement.iframe_heightify (https://superyesmore.com/front/ondemand.yayditor.min.js:46:46)
iframe_heightify @ ondemand.yayditor.min.js:46`

**Comment by alexduloz** [comment]
Thank you :)
