### ISSUE TITLE
The Pastry Box Project: Add feed <link> element to <head>

### ISSUE THREAD

**Issue by jgarber623** [alexduloz/superyesmore#6]
Hello! Adding this issue here after [asking on Twitter](https://twitter.com/jgarber/status/948748476631994372).

It'd be nice to have The Pastry Box Project's RSS feed added to the `<head>` of all pages in a `<link>` element so that browser extensions, etc. can auto-discover the feed. I believe the markup would look something like:

```html
<link rel="alternate" title="The Pastry Box Project – SuperYesMore" type="application/rss+xml" href="https://superyesmore.com/publication/the-pastry-box-project-b0b6f27b41226ac8619212601b8fa48b/feed/rss2">
```

Thanks for considering this addition and _many_ thanks for operating such a great site!

**Comment by alexduloz** [comment]
Added :) Thank you so much. I will close the issue when everything goes live with a few other improvements.

And thanks for the kind words :)

**Comment by jgarber623** [comment]
Looks like this one's resolved. Thanks again!
