### ISSUE TITLE
Meta are kind of weird :D

### ISSUE THREAD

**Issue by geoffreycrofte** [alexduloz/superyesmore#8]
Hello Alex,
It's me again, ha ha :)

I was planning sharing of an article on buffer when I saw this:

<img width="350" alt="screen shot 2018-02-12 at 13 57 47" src="https://user-images.githubusercontent.com/452767/36097944-4d7599a2-0ffd-11e8-855a-3fd1c5cfd619.png">

I think it comes directly from that: 

<img width="988" alt="Strange HTML in meta description" src="https://user-images.githubusercontent.com/452767/36097939-49e25604-0ffd-11e8-90cd-5fa69db7f582.png">

Good luck with the fix, and thank you.

**Comment by geoffreycrofte** [comment]
@alexduloz by the way, do you have private repository where I could contribute? (code contribution, I mean)

**Comment by alexduloz** [comment]
Thank you so much for the heads-up. I'm out of town and mainly operating from my iPhone's wifi. I've fixed the issue, but I will not commit before the end of the week. If you don't see me close this issue and it comes to back to your mind, please don't hesitate to ping me.

I don't have a private repo, although it may be a good idea. I'm deeply refactoring the CMS and I think it will be a good time to have a private repo when I'm ready. With a bit of documentation. But thank you so much for offering to contribute. In the meantime, if you spot things that can be improved, please don't hesitate.

That being said, I will do my best to upload our editor. Mainly javascript, but if people want to contribute, that would be sweet.

:)
